adapt-it/adapt-it-mobile

www/js/views/AdaptViews.js

Escape input strings to prevent  unauthorized scripts from executing.
Unescaped  before storing in KB to maintain input text  (e.g. quotes).  That seems to work, but I also used Regular Expressions to change back specific  characters, that is commented out now. 
Note that this does not prevent  the execution of a script typed by the user directly into a target field.

Escape input - Issue #136

---

www/js/utils/languages.js
www/tpl/LanguagesList.html

Both 3-letter and 2-letter (when available) language codes are defined
in languages.js; to address this, the 2-letter code is displayed and
selected if it exists.

Fix for #161

---

www/config.xml

PG build break — see
https://github.com/litehelpers/Cordova-sqlite-storage/issues/477

Update sqlite plugin to PG Build compatible fork

---

merges/ios/res/css/overrides.css
www/js/views/AdaptViews.js
www/tpl/Chapter.html

There was a name collision between the Next/Previous buttons for the
Adaptation toolbar and the Create Project wizard buttons. Changed the
name for the toolbar, so that the overrides.css file would only hide
that set.

Fix issue #188

---

www/js/views/DocumentViews.js

Output files are now in a subdirectory of the documents, shared,
external root or data directory (depending on the platform) labeled
`AIM_Exports_<rfc>` where `<rfc>` is the RFC 5646 language code for the
target language. This should differentiate the output texts from other
documents. I’ll be updating the wiki with the directory info.

Fix #194, fix #141

---

www/config.xml
www/js/views/AdaptViews.js

Another possible way to address #192 - move the scrollable area down
based on the height and offset of the toolbar above it.

Work on #192

---

www/js/views/AdaptViews.js

Call helper method to address “fat finger” selections on touch devices
(it’s already being called for the mouse). While I’m not seeing issues
on my touch devices, it’s possible this is causing the problems Bruce
is seeing.

Missed a touchend event

---

www/config.xml

diagnostic plugin wasn’t being added to the PhoneGap build.

PG build fix

---

www/js/views/AdaptViews.js

This was working earlier, but some of the selection logic had changed.
Updated the selection points to select the start and end of the strip.

Double-tap selection off by one

---

www/js/utils/HandlebarHelpers.js
www/js/views/AdaptViews.js
www/res/css/styles.css
www/tpl/SourcePhraseList.html

Also add a section head style for chapter and verse that follows the wrap at USFM break, so that chapter and verse numbers appear on a new line
Fixes # .
-
-
-

Keep chapter and verse number with text

---

www/js/views/DocumentViews.js

Remove the file extension when trying to guess a book name; also make better guesses for the chapter and book names when we're working with a scripture portion.
Fixes # .
-
-
-

File Import code cleanup

---

www/js/views/AdaptViews.js

Adding / removing phrases from the KB wasn't catching some cases; made the autoRemoveCaps calls consistent between save and remove calls.
Fixes # .
-
-
-

Fix some KB phrase weirdness

---

www/js/Application.js
www/js/views/AdaptViews.js

Fixed a couple robustness issues with the long-press selection:
- cleared out the long-press flags before  calling movecursor() in the forward / backward button methods
- called the parent pile's event handler if the user releases in a target field AFTER the user has already selected the first pile in a long-press selection.
Fixes # .
-
-
-

Issue #354

---

www/config.xml
www/js/Application.js

Android build number now separated from the milestone build (once build number goes live -- even in beta -- it can't be reused).
Fixes # .
-
-
-

Update build numbers on iOS, Android

---

www/js/views/ProjectViews.js
www/locales/dev/translation.json
www/locales/en/translation.json
www/locales/es/translation.json
www/locales/fr/translation.json
www/locales/hi/translation.json
www/locales/pt/translation.json
www/locales/tpi/translation.json

Fixes #359  .
Here we're not completely disallowing users from changing the source or target language / dialect, in the off chance that they need to correct something that was in error (the language code getting an update, or the language name being offensive and needing to be fixed, etc.). 
Instead, AIM now gives a warning to _not_ change the source and target language to create a new translation project, and directs them to the proper place to create a new project (Settings > Manage Projects).

Add warning to source/target language settings page

---

config.xml
package.json
www/js/Application.js

A couple changes:
- bump iOS build (first iOS submission was missing a couple App Store icons)
- incorporate fix for #442 
- Turn off in-place editing support for iOS (we don't have the privs to do so)

Prep 1.5.0 release

---

config.xml
www/js/Application.js

For iOS, the build number is an incremental number for each release. The app store recently started enforcing this schema; since this is the second working build submitted to the App Store, set the build number to (2).

Update iOS build versioning

---

config.xml
www/js/Application.js

Apple glitch with the latest Xcode (15.0.1 -- Apple has it flagged as a beta for some reason). Solution was to downgrade to Xcode 15.0 and submit a new version. No other code changes.
Fixes # .
-
-
-

Bump iOS build number

---

.github/workflows/main.yml

Looks like the older build nodes got built here anyway.
Fixes # .
-
-
-

Update to 16.x

---

package.json
www/js/views/DocumentViews.js

Automated builds have been updated on github to use gulp 4.0.0; had to make a couple tweaks to the package.json file. Also removed a dup directory entry in DocumentViews.js

Automated build changes

---

config.xml
www/js/Application.js

Accidentally added the .APK instead of the .AAB to the Google Play store. Needed to bump the Android build to 56 for 1.16.3 in order to release the .AAB instead. :/

Oops / Android bump needed

---

config.xml
package.json
www/js/Application.js
www/js/views/AdaptViews.js

Fixes #600, #601 .
- Gloss navigation now looks at the gloss field in each pile to find the next empty slot.
- Fixed a few issues with FT navigation. Should move to one past the current selection, and alert the user when FT is done for the chapter.
- Enable / disable the navigation buttons when the FT editor edit area is selected / blurred.
- Also bumped the version to 1.17.3 (62), and update to the latest cordova-ios (7.1.1)

Fix #600, 601

---

www/js/views/AdaptViews.js

Not needed there, and causing Android to not respond to next/prev clicks

Remove prev/next disable calls in unselectedFT

---

www/js/Application.js
www/js/views/ProjectViews.js

- For import and search pages, fetch only the books/chapters for the current project 
- For new projects created from the Manage Projects settings page, return to the home page when finished
- For switching between projects, return to the home page

A couple more fixes for #604
