adapt-it/adapt-it-mobile

- www/config.xml
Also add splash screen plugin; pin the plugins to specific versions to
avoid other breaking API changes.
> Version 0.5.6

- www/js/utils/usfm.js
- www/js/views/DocumentViews.js
> Sync with local changes

- www/js/main.js
Looks like I might have skipped a file on a previous checkin.
Featherlight gallery was missing dependencies on featherlight and
jquery.
> Fix featherlight deps

- www/js/utils/HandlebarHelpers.js
- www/res/css/styles.css
- www/tpl/FilterList.html
Added a filter count, styled the next/prev arrows to be visible, set
colors on the can/cannot set the filter text.
> #142 styling

- www/config.xml
- www/js/views/AdaptViews.js
- www/res/css/styles.css
Also fix filtering — the event wasn’t propagating properly.
> bump version to 0.9.9

- www/config.xml
> Remove version tag

- package.json
- www/config.xml
- www/js/views/AdaptViews.js
- www/res/css/styles.css
- Bumped version to 1.0.0b12 (Android build code 23)
- Disallow wrapping of markers (this was causing the rendering to get wonky for longer marker sets)
- Made sure the Filter icon display followed the RTL script direction
> Fix a couple rendering bugs

- www/js/Application.js
- www/js/views/DocumentViews.js
- www/res/css/styles.css
> Sanity check for missing book name

- www/js/views/AdaptViews.js
- www/res/css/styles.css
Also removed a reference to the (no longer existent) toolbar that was throwing an exception in the AddStyleRules method.
Fixes # .
-
-
-
> Fix RTL wrap / display

- www/js/views/AdaptViews.js
- www/res/css/styles.css
- RTL flow now ONLY depends on source language
- Add USFM /s# to list of markers that start on newline
- Various and sundry CSS cleanup
> Work on #259

- www/js/views/AdaptViews.js
- www/res/css/styles.css
123 of them in total; we were handling 11 before.
Fixes # .
-
-
-
> Add markers that require line breaks

- www/config.xml
- www/js/views/DocumentViews.js
- www/js/views/HomeViews.js
Also clean up the book name guess for text file import, and fix a typo for cancelling the UI language from the welcome view
Fixes # .
-
-
-
> Bump revision

- www/js/views/DocumentViews.js
- www/tpl/SourcePhraseList.html
> Code cleanup

- package.json
- www/config.xml
Looks like cordova CLI did some tweaking under the hood -- reverting
Fixes # .
-
-
-
> PG build fix

- www/js/views/AdaptViews.js
- www/js/views/ProjectViews.js
- www/locales/fr/translation.json
- www/locales/pt/translation.json
> Fold in code changes

- LICENSE
- README.md
- www/config.xml
- www/js/views/AdaptViews.js
Fixes #343. Also bumps revision number and copyright date.
> Merge changes

- www/config.xml
Also link to upstream version of cordova-clipboard (our changes were accepted in a PR)
Fixes # .
-
-
-
> bump version

- www/config.xml
- www/js/views/AdaptViews.js
- www/js/views/DocumentViews.js
- www/locales/dev/translation.json
- www/locales/en/translation.json
- www/locales/es/translation.json
- www/locales/fr/translation.json
- www/locales/hi/translation.json
- www/locales/pt/translation.json
- www/locales/tpi/translation.json
> RC4 bug fixes

- merges/ios/res/css/overrides.css
- www/js/utils/HandlebarHelpers.js
- www/js/views/DocumentViews.js
- www/res/css/styles.css
- www/tpl/Chapter.html
- www/tpl/Home.html
> USFM, XML import tweaks; iOS notch UI

- package.json
- www/config.xml
- www/js/Application.js
> Bump revision for patch release

- package.json
- www/config.xml
- www/js/Application.js
- www/js/views/DocumentViews.js
- www/locales/dev/translation.json
- www/locales/en/translation.json
- www/locales/es/translation.json
- www/locales/fr/translation.json
- www/locales/hi/translation.json
- www/locales/pt/translation.json
- www/locales/tpi/translation.json
- www/res/css/images/kb.svg
- www/res/css/styles.css
- www/res/svg/kb.svg
- www/tpl/ExportChooseFormat.html
> TMX import/export, updates to iOS, Android

- merges/ios/res/css/overrides.css
- package.json
- www/js/Application.js
- www/js/main.js
- www/js/views/AdaptViews.js
- www/js/views/ProjectViews.js
- www/js/views/SearchViews.js
- www/lib/spectrum.js
- www/res/css/spectrum.css
Fixes issues found during testing - iOS and Android. See individual checkins for bug details.
> Testing bug fixes - 1.3.0

- merges/ios/res/css/overrides.css
- www/js/models/sql/chapter.js
- www/js/views/AdaptViews.js
- www/js/views/SearchViews.js
Fixed a couple issues found during testing:
- iOS / fixed toolbar height issues with notched + non-notched devices
- Lookup/browse chapters - lists were not working for documents with spaces in them (e.g., "1 John") because we were searching by name. Changed this to search by book ID instead.
> Testing bug fixes

- config.xml
- www/js/Application.js
- www/js/views/ProjectViews.js
- www/locales/dev/translation.json
- www/locales/en/translation.json
- www/locales/es/translation.json
- www/locales/fr/translation.json
- www/locales/hi/translation.json
- www/locales/pt/translation.json
- www/locales/tpi/translation.json
> Updates to source/target language page text

- www/js/Application.js
- www/res/css/styles.css
Fixed spacing for preview mode; also bumped version # displayed in general / editor settings page.
> Minor edits / bump revision

- config.xml
- merges/ios/res/css/overrides.css
- package.json
- www/js/Application.js
- www/js/main.js
- www/js/views/AdaptViews.js
- www/js/views/DocumentViews.js
- www/res/css/pageslider.css
> Merge unit test fixes

- config.xml
- www/js/Application.js
> Release 1.5.0 prep

- LICENSE
- config.xml
- package.json
- www/js/Application.js
> Copyright, version bump

- package.json
- www/js/Application.js
- www/js/utils/HandlebarHelpers.js
- www/js/views/AdaptViews.js
- www/js/views/DocumentViews.js
- www/js/views/ProjectViews.js
- Fix #456: Bump iOS build version; upgrade cordova-android to latest and move to a fork of the socialsharing plugin that supports Android 12's required android:exported tag.
- Fix #457: Add polyfill utility method in Application.js to generate UUIDs. 
Fixes #456, #457.
> Fix #456, #457

- config.xml
- www/js/Application.js
- www/js/views/DocumentViews.js
Version submitted to Apple/Google play stores. Hopefully this is the one...
> 1.7.0 rc(4)

- config.xml
- hooks/after_prepare/uglify.js
- package.json
- www/js/models/sql/project.js
- www/js/views/DocumentViews.js
- www/locales/dev/translation.json
- www/locales/en/translation.json
- www/locales/es/translation.json
- www/locales/fr/translation.json
- www/locales/hi/translation.json
- www/locales/pt/translation.json
- www/locales/tpi/translation.json
> Various and sundry changes

- README.md
> System requirements for Android (8.0 or later)

- www/js/views/AdaptViews.js
- www/js/views/DocumentViews.js
Fixes #499, #500 .
- Build book name from localized Scripture ID when importing Adapt It XML document file
- Fix logic error in double-tap detection / handling, so that both mobile and browser blocks use the same code.
> Fix #499, #500

- www/js/Application.js
- www/js/views/DocumentViews.js
- www/locales/dev/translation.json
- www/locales/en/translation.json
- www/locales/es/translation.json
- www/locales/fr/translation.json
- www/locales/pt/translation.json
- www/locales/tpi/translation.json
Work on #506 -- basic import support might be done at this point. I need to test against more real-world data.
> Code checkin / update

- build-aim.sh
- config.xml
- package.json
- www/js/Application.js
> Updates to latest android and file plugins

- config.xml
- package.json
- www/js/Application.js
> Bump version to 1.13.0

- config.xml
- package.json
- www/js/Application.js
- www/js/views/DocumentViews.js
- www/js/views/SearchViews.js
> Fix for #526, #527, #528

- README.md
> Update links to PT and USFM

- www/js/views/DocumentViews.js
- www/js/views/ProjectViews.js
Android - expand available selection list to */*
Fixes # .
-
-
-
> Supplemental work on #538

- www/index.html
- www/js/views/ProjectViews.js
Android - save/retrieve projectID to enable switch between projects
Also fix a failed query for favicon.ico (not in project, but Android was looking for it because it's in a web app).
> Supplemental changes for #539

- config.xml
- www/js/Application.js
- www/js/views/DocumentViews.js
Bump iOS build for TestFlight; also add a couple fixes for KB import.
> Moar test fixes

- config.xml
- www/js/Application.js
> Bump version (1.15.1)

- www/js/views/ProjectViews.js
- www/js/views/SearchViews.js
- www/tpl/NewTU.html
- www/tpl/ProjectCases.html
A couple changes to the KB edit translation code, as well as removing some auto-caps from edit fields that didn't need it enabled.
> Fix #569, #570

- config.xml
- package.json
- www/js/Application.js
- www/res/electron/settings.json
Reworking changes as patch release 1.16.1.
> Bump version to 1.16.1

- config.xml
- package.json
- www/js/Application.js
> Bump version (1.16.2)

- config.xml
- package.json
- www/js/Application.js
- www/js/views/AdaptViews.js
- New version 1.17.0
- Found a couple more places where punctuation wasn't being stripped out properly, leading to duplicate punctuation when the user moved the cursor.
> Bump version, fix punctuation issue

- config.xml
- package.json
- www/js/models/sql/project.js
- www/res/electron/settings.json
Fixed a data type issue in the Project object that might have been the cause of a bug on the first document import. Still needs more end-to-end testing.
> Work on #604

- ISSUE_TEMPLATE.md
- LICENSE
- config.xml
- package.json
- www/js/Application.js
- www/js/models/sql/project.js
- www/res/css/styles.css
- www/tpl/ProjectCases.html
- www/tpl/ProjectPunctuation.html
Fixes #614, #615.
- Increase font size in Punctuation and Case wizard steps, and make the font the highest weight.
- Increate font size in the language suggestion dropdown for the subtext, and make the text blue to differentiate from the top line language text
- Also move to Cordova-android 14.0.0. This allows us to support Cordova 15 devices with edge-to-edge support.
More unit testing is needed for the Android side.
> Fix #614, #615
